/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing CollectionItemAttributesInnerValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollectionItemAttributesInnerValueTests
    {
        // TODO uncomment below to declare an instance variable for CollectionItemAttributesInnerValue
        //private CollectionItemAttributesInnerValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CollectionItemAttributesInnerValue
            //instance = new CollectionItemAttributesInnerValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CollectionItemAttributesInnerValue
        /// </summary>
        [Test]
        public void CollectionItemAttributesInnerValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CollectionItemAttributesInnerValue
            //Assert.IsInstanceOf(typeof(CollectionItemAttributesInnerValue), instance);
        }



    }

}
