/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing CreateCollectionItemRequestAttributesInnerValue
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCollectionItemRequestAttributesInnerValueTests
    {
        // TODO uncomment below to declare an instance variable for CreateCollectionItemRequestAttributesInnerValue
        //private CreateCollectionItemRequestAttributesInnerValue instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateCollectionItemRequestAttributesInnerValue
            //instance = new CreateCollectionItemRequestAttributesInnerValue();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateCollectionItemRequestAttributesInnerValue
        /// </summary>
        [Test]
        public void CreateCollectionItemRequestAttributesInnerValueInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreateCollectionItemRequestAttributesInnerValue
            //Assert.IsInstanceOf(typeof(CreateCollectionItemRequestAttributesInnerValue), instance);
        }



    }

}
