/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing CreateContractRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateContractRequestTests
    {
        // TODO uncomment below to declare an instance variable for CreateContractRequest
        //private CreateContractRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreateContractRequest
            //instance = new CreateContractRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreateContractRequest
        /// </summary>
        [Test]
        public void CreateContractRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" CreateContractRequest
            //Assert.IsInstanceOf(typeof(CreateContractRequest), instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Abi'
        /// </summary>
        [Test]
        public void AbiTest()
        {
            // TODO unit test for the property 'Abi'
        }
        /// <summary>
        /// Test the property 'Chain'
        /// </summary>
        [Test]
        public void ChainTest()
        {
            // TODO unit test for the property 'Chain'
        }

    }

}
