/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing EcosystemModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EcosystemModelTests
    {
        // TODO uncomment below to declare an instance variable for EcosystemModel
        //private EcosystemModel instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EcosystemModel
            //instance = new EcosystemModel();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EcosystemModel
        /// </summary>
        [Test]
        public void EcosystemModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" EcosystemModel
            //Assert.IsInstanceOf(typeof(EcosystemModel), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'IconImageUrl'
        /// </summary>
        [Test]
        public void IconImageUrlTest()
        {
            // TODO unit test for the property 'IconImageUrl'
        }
        /// <summary>
        /// Test the property 'CoverImageUrl'
        /// </summary>
        [Test]
        public void CoverImageUrlTest()
        {
            // TODO unit test for the property 'CoverImageUrl'
        }
        /// <summary>
        /// Test the property 'PrimaryColorHex'
        /// </summary>
        [Test]
        public void PrimaryColorHexTest()
        {
            // TODO unit test for the property 'PrimaryColorHex'
        }
        /// <summary>
        /// Test the property 'PublishedKey'
        /// </summary>
        [Test]
        public void PublishedKeyTest()
        {
            // TODO unit test for the property 'PublishedKey'
        }
        /// <summary>
        /// Test the property 'SecretKey'
        /// </summary>
        [Test]
        public void SecretKeyTest()
        {
            // TODO unit test for the property 'SecretKey'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

    }

}
