/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing GetCurrencyFees200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetCurrencyFees200ResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetCurrencyFees200Response
        //private GetCurrencyFees200Response instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetCurrencyFees200Response
            //instance = new GetCurrencyFees200Response();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetCurrencyFees200Response
        /// </summary>
        [Test]
        public void GetCurrencyFees200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" GetCurrencyFees200Response
            //Assert.IsInstanceOf(typeof(GetCurrencyFees200Response), instance);
        }


        /// <summary>
        /// Test the property 'RecipientAddress'
        /// </summary>
        [Test]
        public void RecipientAddressTest()
        {
            // TODO unit test for the property 'RecipientAddress'
        }
        /// <summary>
        /// Test the property 'BasisPoints'
        /// </summary>
        [Test]
        public void BasisPointsTest()
        {
            // TODO unit test for the property 'BasisPoints'
        }
        /// <summary>
        /// Test the property 'FixedAmount'
        /// </summary>
        [Test]
        public void FixedAmountTest()
        {
            // TODO unit test for the property 'FixedAmount'
        }
        /// <summary>
        /// Test the property 'CapAmount'
        /// </summary>
        [Test]
        public void CapAmountTest()
        {
            // TODO unit test for the property 'CapAmount'
        }

    }

}
