/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing RemovePlayerConnectedWalletRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RemovePlayerConnectedWalletRequestTests
    {
        // TODO uncomment below to declare an instance variable for RemovePlayerConnectedWalletRequest
        //private RemovePlayerConnectedWalletRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RemovePlayerConnectedWalletRequest
            //instance = new RemovePlayerConnectedWalletRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RemovePlayerConnectedWalletRequest
        /// </summary>
        [Test]
        public void RemovePlayerConnectedWalletRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" RemovePlayerConnectedWalletRequest
            //Assert.IsInstanceOf(typeof(RemovePlayerConnectedWalletRequest), instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Test]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Test]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }
        /// <summary>
        /// Test the property 'Chain'
        /// </summary>
        [Test]
        public void ChainTest()
        {
            // TODO unit test for the property 'Chain'
        }

    }

}
