/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing SetPlayerDataRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetPlayerDataRequestTests
    {
        // TODO uncomment below to declare an instance variable for SetPlayerDataRequest
        //private SetPlayerDataRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SetPlayerDataRequest
            //instance = new SetPlayerDataRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SetPlayerDataRequest
        /// </summary>
        [Test]
        public void SetPlayerDataRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SetPlayerDataRequest
            //Assert.IsInstanceOf(typeof(SetPlayerDataRequest), instance);
        }


        /// <summary>
        /// Test the property 'ProtectedData'
        /// </summary>
        [Test]
        public void ProtectedDataTest()
        {
            // TODO unit test for the property 'ProtectedData'
        }
        /// <summary>
        /// Test the property 'PublicData'
        /// </summary>
        [Test]
        public void PublicDataTest()
        {
            // TODO unit test for the property 'PublicData'
        }

    }

}
