/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing SetShopOfferRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SetShopOfferRequestTests
    {
        // TODO uncomment below to declare an instance variable for SetShopOfferRequest
        //private SetShopOfferRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SetShopOfferRequest
            //instance = new SetShopOfferRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SetShopOfferRequest
        /// </summary>
        [Test]
        public void SetShopOfferRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" SetShopOfferRequest
            //Assert.IsInstanceOf(typeof(SetShopOfferRequest), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'InputCollectionAddress'
        /// </summary>
        [Test]
        public void InputCollectionAddressTest()
        {
            // TODO unit test for the property 'InputCollectionAddress'
        }
        /// <summary>
        /// Test the property 'InputCollectionId'
        /// </summary>
        [Test]
        public void InputCollectionIdTest()
        {
            // TODO unit test for the property 'InputCollectionId'
        }
        /// <summary>
        /// Test the property 'InputCollectionItemIds'
        /// </summary>
        [Test]
        public void InputCollectionItemIdsTest()
        {
            // TODO unit test for the property 'InputCollectionItemIds'
        }
        /// <summary>
        /// Test the property 'InputCollectionItemAmounts'
        /// </summary>
        [Test]
        public void InputCollectionItemAmountsTest()
        {
            // TODO unit test for the property 'InputCollectionItemAmounts'
        }
        /// <summary>
        /// Test the property 'InputCurrencyAddress'
        /// </summary>
        [Test]
        public void InputCurrencyAddressTest()
        {
            // TODO unit test for the property 'InputCurrencyAddress'
        }
        /// <summary>
        /// Test the property 'InputCurrencyId'
        /// </summary>
        [Test]
        public void InputCurrencyIdTest()
        {
            // TODO unit test for the property 'InputCurrencyId'
        }
        /// <summary>
        /// Test the property 'InputCurrencyAmount'
        /// </summary>
        [Test]
        public void InputCurrencyAmountTest()
        {
            // TODO unit test for the property 'InputCurrencyAmount'
        }
        /// <summary>
        /// Test the property 'OutputCollectionAddress'
        /// </summary>
        [Test]
        public void OutputCollectionAddressTest()
        {
            // TODO unit test for the property 'OutputCollectionAddress'
        }
        /// <summary>
        /// Test the property 'OutputCollectionId'
        /// </summary>
        [Test]
        public void OutputCollectionIdTest()
        {
            // TODO unit test for the property 'OutputCollectionId'
        }
        /// <summary>
        /// Test the property 'OutputCollectionItemIds'
        /// </summary>
        [Test]
        public void OutputCollectionItemIdsTest()
        {
            // TODO unit test for the property 'OutputCollectionItemIds'
        }
        /// <summary>
        /// Test the property 'OutputCollectionItemAmounts'
        /// </summary>
        [Test]
        public void OutputCollectionItemAmountsTest()
        {
            // TODO unit test for the property 'OutputCollectionItemAmounts'
        }
        /// <summary>
        /// Test the property 'OutputCurrencyAddress'
        /// </summary>
        [Test]
        public void OutputCurrencyAddressTest()
        {
            // TODO unit test for the property 'OutputCurrencyAddress'
        }
        /// <summary>
        /// Test the property 'OutputCurrencyId'
        /// </summary>
        [Test]
        public void OutputCurrencyIdTest()
        {
            // TODO unit test for the property 'OutputCurrencyId'
        }
        /// <summary>
        /// Test the property 'OutputCurrencyAmount'
        /// </summary>
        [Test]
        public void OutputCurrencyAmountTest()
        {
            // TODO unit test for the property 'OutputCurrencyAmount'
        }
        /// <summary>
        /// Test the property 'MaxUses'
        /// </summary>
        [Test]
        public void MaxUsesTest()
        {
            // TODO unit test for the property 'MaxUses'
        }

    }

}
