/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing TransferContractOwnershipRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransferContractOwnershipRequestTests
    {
        // TODO uncomment below to declare an instance variable for TransferContractOwnershipRequest
        //private TransferContractOwnershipRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of TransferContractOwnershipRequest
            //instance = new TransferContractOwnershipRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TransferContractOwnershipRequest
        /// </summary>
        [Test]
        public void TransferContractOwnershipRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" TransferContractOwnershipRequest
            //Assert.IsInstanceOf(typeof(TransferContractOwnershipRequest), instance);
        }


        /// <summary>
        /// Test the property 'OwnerAddress'
        /// </summary>
        [Test]
        public void OwnerAddressTest()
        {
            // TODO unit test for the property 'OwnerAddress'
        }

    }

}
