/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing UpdateGame200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateGame200ResponseTests
    {
        // TODO uncomment below to declare an instance variable for UpdateGame200Response
        //private UpdateGame200Response instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UpdateGame200Response
            //instance = new UpdateGame200Response();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UpdateGame200Response
        /// </summary>
        [Test]
        public void UpdateGame200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" UpdateGame200Response
            //Assert.IsInstanceOf(typeof(UpdateGame200Response), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'WalletId'
        /// </summary>
        [Test]
        public void WalletIdTest()
        {
            // TODO unit test for the property 'WalletId'
        }
        /// <summary>
        /// Test the property 'FundingWalletId'
        /// </summary>
        [Test]
        public void FundingWalletIdTest()
        {
            // TODO unit test for the property 'FundingWalletId'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Rpcs'
        /// </summary>
        [Test]
        public void RpcsTest()
        {
            // TODO unit test for the property 'Rpcs'
        }
        /// <summary>
        /// Test the property 'RedirectUris'
        /// </summary>
        [Test]
        public void RedirectUrisTest()
        {
            // TODO unit test for the property 'RedirectUris'
        }
        /// <summary>
        /// Test the property 'IconImageUrl'
        /// </summary>
        [Test]
        public void IconImageUrlTest()
        {
            // TODO unit test for the property 'IconImageUrl'
        }
        /// <summary>
        /// Test the property 'CoverImageUrl'
        /// </summary>
        [Test]
        public void CoverImageUrlTest()
        {
            // TODO unit test for the property 'CoverImageUrl'
        }
        /// <summary>
        /// Test the property 'PrimaryColorHex'
        /// </summary>
        [Test]
        public void PrimaryColorHexTest()
        {
            // TODO unit test for the property 'PrimaryColorHex'
        }
        /// <summary>
        /// Test the property 'PublishedKey'
        /// </summary>
        [Test]
        public void PublishedKeyTest()
        {
            // TODO unit test for the property 'PublishedKey'
        }
        /// <summary>
        /// Test the property 'SecretKey'
        /// </summary>
        [Test]
        public void SecretKeyTest()
        {
            // TODO unit test for the property 'SecretKey'
        }
        /// <summary>
        /// Test the property 'Verified'
        /// </summary>
        [Test]
        public void VerifiedTest()
        {
            // TODO unit test for the property 'Verified'
        }
        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Test]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Test]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
        /// <summary>
        /// Test the property 'WalletDecryptKey'
        /// </summary>
        [Test]
        public void WalletDecryptKeyTest()
        {
            // TODO unit test for the property 'WalletDecryptKey'
        }

    }

}
