/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing WithdrawFromShopRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WithdrawFromShopRequestTests
    {
        // TODO uncomment below to declare an instance variable for WithdrawFromShopRequest
        //private WithdrawFromShopRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WithdrawFromShopRequest
            //instance = new WithdrawFromShopRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WithdrawFromShopRequest
        /// </summary>
        [Test]
        public void WithdrawFromShopRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WithdrawFromShopRequest
            //Assert.IsInstanceOf(typeof(WithdrawFromShopRequest), instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'WalletId'
        /// </summary>
        [Test]
        public void WalletIdTest()
        {
            // TODO unit test for the property 'WalletId'
        }
        /// <summary>
        /// Test the property 'CurrencyAddress'
        /// </summary>
        [Test]
        public void CurrencyAddressTest()
        {
            // TODO unit test for the property 'CurrencyAddress'
        }
        /// <summary>
        /// Test the property 'CurrencyId'
        /// </summary>
        [Test]
        public void CurrencyIdTest()
        {
            // TODO unit test for the property 'CurrencyId'
        }
        /// <summary>
        /// Test the property 'CollectionAddress'
        /// </summary>
        [Test]
        public void CollectionAddressTest()
        {
            // TODO unit test for the property 'CollectionAddress'
        }
        /// <summary>
        /// Test the property 'CollectionId'
        /// </summary>
        [Test]
        public void CollectionIdTest()
        {
            // TODO unit test for the property 'CollectionId'
        }
        /// <summary>
        /// Test the property 'ItemIds'
        /// </summary>
        [Test]
        public void ItemIdsTest()
        {
            // TODO unit test for the property 'ItemIds'
        }

    }

}
