/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.MetaFab.Api;
using Org.MetaFab.Model;
using Org.MetaFab.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.MetaFab.Test
{
    /// <summary>
    ///  Class for testing WriteContractRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WriteContractRequestTests
    {
        // TODO uncomment below to declare an instance variable for WriteContractRequest
        //private WriteContractRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WriteContractRequest
            //instance = new WriteContractRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WriteContractRequest
        /// </summary>
        [Test]
        public void WriteContractRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" WriteContractRequest
            //Assert.IsInstanceOf(typeof(WriteContractRequest), instance);
        }


        /// <summary>
        /// Test the property 'Func'
        /// </summary>
        [Test]
        public void FuncTest()
        {
            // TODO unit test for the property 'Func'
        }
        /// <summary>
        /// Test the property 'Args'
        /// </summary>
        [Test]
        public void ArgsTest()
        {
            // TODO unit test for the property 'Args'
        }

    }

}
