/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.MetaFab.Client.OpenAPIDateConverter;

namespace Org.MetaFab.Model
{
    /// <summary>
    /// BatchTransferCollectionItemsRequest
    /// </summary>
    [DataContract]
    public partial class BatchTransferCollectionItemsRequest :  IEquatable<BatchTransferCollectionItemsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchTransferCollectionItemsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BatchTransferCollectionItemsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchTransferCollectionItemsRequest" /> class.
        /// </summary>
        /// <param name="addresses">An array of valid EVM based addresses to transfer items to..</param>
        /// <param name="walletIds">An array of wallet ids within the MetaFab ecosystem to transfer items to..</param>
        /// <param name="itemIds">An array of unique itemIds to transfer. Each recipient will receive the same set of items provided. (required).</param>
        /// <param name="quantities">The quantities of each unique itemId to transfer. Each recipient will receive the same quantities of items provided. (required).</param>
        public BatchTransferCollectionItemsRequest(List<string> addresses = default(List<string>), List<string> walletIds = default(List<string>), List<int> itemIds = default(List<int>), List<int> quantities = default(List<int>))
        {
            // to ensure "itemIds" is required (not null)
            if (itemIds == null)
            {
                throw new InvalidDataException("itemIds is a required property for BatchTransferCollectionItemsRequest and cannot be null");
            }
            else
            {
                this.ItemIds = itemIds;
            }

            // to ensure "quantities" is required (not null)
            if (quantities == null)
            {
                throw new InvalidDataException("quantities is a required property for BatchTransferCollectionItemsRequest and cannot be null");
            }
            else
            {
                this.Quantities = quantities;
            }

            this.Addresses = addresses;
            this.WalletIds = walletIds;
        }

        /// <summary>
        /// An array of valid EVM based addresses to transfer items to.
        /// </summary>
        /// <value>An array of valid EVM based addresses to transfer items to.</value>
        [DataMember(Name="addresses", EmitDefaultValue=false)]
        public List<string> Addresses { get; set; }

        /// <summary>
        /// An array of wallet ids within the MetaFab ecosystem to transfer items to.
        /// </summary>
        /// <value>An array of wallet ids within the MetaFab ecosystem to transfer items to.</value>
        [DataMember(Name="walletIds", EmitDefaultValue=false)]
        public List<string> WalletIds { get; set; }

        /// <summary>
        /// An array of unique itemIds to transfer. Each recipient will receive the same set of items provided.
        /// </summary>
        /// <value>An array of unique itemIds to transfer. Each recipient will receive the same set of items provided.</value>
        [DataMember(Name="itemIds", EmitDefaultValue=true)]
        public List<int> ItemIds { get; set; }

        /// <summary>
        /// The quantities of each unique itemId to transfer. Each recipient will receive the same quantities of items provided.
        /// </summary>
        /// <value>The quantities of each unique itemId to transfer. Each recipient will receive the same quantities of items provided.</value>
        [DataMember(Name="quantities", EmitDefaultValue=true)]
        public List<int> Quantities { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BatchTransferCollectionItemsRequest {\n");
            sb.Append("  Addresses: ").Append(Addresses).Append("\n");
            sb.Append("  WalletIds: ").Append(WalletIds).Append("\n");
            sb.Append("  ItemIds: ").Append(ItemIds).Append("\n");
            sb.Append("  Quantities: ").Append(Quantities).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BatchTransferCollectionItemsRequest);
        }

        /// <summary>
        /// Returns true if BatchTransferCollectionItemsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of BatchTransferCollectionItemsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BatchTransferCollectionItemsRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Addresses == input.Addresses ||
                    this.Addresses != null &&
                    input.Addresses != null &&
                    this.Addresses.SequenceEqual(input.Addresses)
                ) && 
                (
                    this.WalletIds == input.WalletIds ||
                    this.WalletIds != null &&
                    input.WalletIds != null &&
                    this.WalletIds.SequenceEqual(input.WalletIds)
                ) && 
                (
                    this.ItemIds == input.ItemIds ||
                    this.ItemIds != null &&
                    input.ItemIds != null &&
                    this.ItemIds.SequenceEqual(input.ItemIds)
                ) && 
                (
                    this.Quantities == input.Quantities ||
                    this.Quantities != null &&
                    input.Quantities != null &&
                    this.Quantities.SequenceEqual(input.Quantities)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Addresses != null)
                    hashCode = hashCode * 59 + this.Addresses.GetHashCode();
                if (this.WalletIds != null)
                    hashCode = hashCode * 59 + this.WalletIds.GetHashCode();
                if (this.ItemIds != null)
                    hashCode = hashCode * 59 + this.ItemIds.GetHashCode();
                if (this.Quantities != null)
                    hashCode = hashCode * 59 + this.Quantities.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
