/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.1.43
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.MetaFab.Client.OpenAPIDateConverter;

namespace Org.MetaFab.Model
{
    /// <summary>
    /// CreateCollectionItemRequestAttributesInner
    /// </summary>
    [DataContract]
    public partial class CreateCollectionItemRequestAttributesInner :  IEquatable<CreateCollectionItemRequestAttributesInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCollectionItemRequestAttributesInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateCollectionItemRequestAttributesInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateCollectionItemRequestAttributesInner" /> class.
        /// </summary>
        /// <param name="traitType">traitType (required).</param>
        /// <param name="value">value (required).</param>
        public CreateCollectionItemRequestAttributesInner(string traitType = default(string), Object value = default(Object))
        {
            // to ensure "traitType" is required (not null)
            if (traitType == null)
            {
                throw new InvalidDataException("traitType is a required property for CreateCollectionItemRequestAttributesInner and cannot be null");
            }
            else
            {
                this.TraitType = traitType;
            }

            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new InvalidDataException("value is a required property for CreateCollectionItemRequestAttributesInner and cannot be null");
            }
            else
            {
                this.Value = value;
            }

            this.Value = value;
        }

        /// <summary>
        /// Gets or Sets TraitType
        /// </summary>
        [DataMember(Name="trait_type", EmitDefaultValue=true)]
        public string TraitType { get; set; }

        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="value", EmitDefaultValue=true)]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateCollectionItemRequestAttributesInner {\n");
            sb.Append("  TraitType: ").Append(TraitType).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateCollectionItemRequestAttributesInner);
        }

        /// <summary>
        /// Returns true if CreateCollectionItemRequestAttributesInner instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateCollectionItemRequestAttributesInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateCollectionItemRequestAttributesInner input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TraitType == input.TraitType ||
                    (this.TraitType != null &&
                    this.TraitType.Equals(input.TraitType))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TraitType != null)
                    hashCode = hashCode * 59 + this.TraitType.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
