/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.MetaFab.Client.OpenAPIDateConverter;

namespace Org.MetaFab.Model
{
    /// <summary>
    /// CreateProfilePlayerRequest
    /// </summary>
    [DataContract]
    public partial class CreateProfilePlayerRequest :  IEquatable<CreateProfilePlayerRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateProfilePlayerRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateProfilePlayerRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateProfilePlayerRequest" /> class.
        /// </summary>
        /// <param name="username">The username to assign to the created player. (required).</param>
        /// <param name="permissions">A properly formatted permissions object that validates against the MetaFab profile permissions schema..</param>
        public CreateProfilePlayerRequest(string username = default(string), Dictionary<string, ProfilePermissionsValue> permissions = default(Dictionary<string, ProfilePermissionsValue>))
        {
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new InvalidDataException("username is a required property for CreateProfilePlayerRequest and cannot be null");
            }
            else
            {
                this.Username = username;
            }

            this.Permissions = permissions;
        }

        /// <summary>
        /// The username to assign to the created player.
        /// </summary>
        /// <value>The username to assign to the created player.</value>
        [DataMember(Name="username", EmitDefaultValue=true)]
        public string Username { get; set; }

        /// <summary>
        /// A properly formatted permissions object that validates against the MetaFab profile permissions schema.
        /// </summary>
        /// <value>A properly formatted permissions object that validates against the MetaFab profile permissions schema.</value>
        [DataMember(Name="permissions", EmitDefaultValue=false)]
        public Dictionary<string, ProfilePermissionsValue> Permissions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreateProfilePlayerRequest {\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreateProfilePlayerRequest);
        }

        /// <summary>
        /// Returns true if CreateProfilePlayerRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreateProfilePlayerRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreateProfilePlayerRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Username == input.Username ||
                    (this.Username != null &&
                    this.Username.Equals(input.Username))
                ) && 
                (
                    this.Permissions == input.Permissions ||
                    this.Permissions != null &&
                    input.Permissions != null &&
                    this.Permissions.SequenceEqual(input.Permissions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Username != null)
                    hashCode = hashCode * 59 + this.Username.GetHashCode();
                if (this.Permissions != null)
                    hashCode = hashCode * 59 + this.Permissions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
