/*
 * MetaFab API
 *
 *  Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.MetaFab.Client.OpenAPIDateConverter;

namespace Org.MetaFab.Model
{
    /// <summary>
    /// TransferCurrencyRequest
    /// </summary>
    [DataContract]
    public partial class TransferCurrencyRequest :  IEquatable<TransferCurrencyRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferCurrencyRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransferCurrencyRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferCurrencyRequest" /> class.
        /// </summary>
        /// <param name="address">A valid EVM based address to transfer currency to. For example, &#x60;0x39cb70F972E0EE920088AeF97Dbe5c6251a9c25D&#x60;..</param>
        /// <param name="walletId">Any wallet id within the MetaFab ecosystem to transfer currency to..</param>
        /// <param name="amount">The amount of currency to transfer. (required).</param>
        /// <param name="reference">An optional uint256 number to reference the transfer. Commonly used to identify transfers intended to pay for game items or services..</param>
        public TransferCurrencyRequest(string address = default(string), string walletId = default(string), decimal amount = default(decimal), decimal reference = default(decimal))
        {
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new InvalidDataException("amount is a required property for TransferCurrencyRequest and cannot be null");
            }
            else
            {
                this.Amount = amount;
            }

            this.Address = address;
            this.WalletId = walletId;
            this.Reference = reference;
        }

        /// <summary>
        /// A valid EVM based address to transfer currency to. For example, &#x60;0x39cb70F972E0EE920088AeF97Dbe5c6251a9c25D&#x60;.
        /// </summary>
        /// <value>A valid EVM based address to transfer currency to. For example, &#x60;0x39cb70F972E0EE920088AeF97Dbe5c6251a9c25D&#x60;.</value>
        [DataMember(Name="address", EmitDefaultValue=false)]
        public string Address { get; set; }

        /// <summary>
        /// Any wallet id within the MetaFab ecosystem to transfer currency to.
        /// </summary>
        /// <value>Any wallet id within the MetaFab ecosystem to transfer currency to.</value>
        [DataMember(Name="walletId", EmitDefaultValue=false)]
        public string WalletId { get; set; }

        /// <summary>
        /// The amount of currency to transfer.
        /// </summary>
        /// <value>The amount of currency to transfer.</value>
        [DataMember(Name="amount", EmitDefaultValue=true)]
        public decimal Amount { get; set; }

        /// <summary>
        /// An optional uint256 number to reference the transfer. Commonly used to identify transfers intended to pay for game items or services.
        /// </summary>
        /// <value>An optional uint256 number to reference the transfer. Commonly used to identify transfers intended to pay for game items or services.</value>
        [DataMember(Name="reference", EmitDefaultValue=false)]
        public decimal Reference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransferCurrencyRequest {\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  WalletId: ").Append(WalletId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Reference: ").Append(Reference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransferCurrencyRequest);
        }

        /// <summary>
        /// Returns true if TransferCurrencyRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TransferCurrencyRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransferCurrencyRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.WalletId == input.WalletId ||
                    (this.WalletId != null &&
                    this.WalletId.Equals(input.WalletId))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.Reference == input.Reference ||
                    (this.Reference != null &&
                    this.Reference.Equals(input.Reference))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                if (this.WalletId != null)
                    hashCode = hashCode * 59 + this.WalletId.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.Reference != null)
                    hashCode = hashCode * 59 + this.Reference.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
