/*
 * MetaFab API
 *
 * Complete MetaFab API references and guides can be found at: https://trymetafab.com
 *
 * The version of the OpenAPI document: 1.5.1
 * Contact: metafabproject@gmail.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.MetaFab.Client.OpenAPIDateConverter;

namespace Org.MetaFab.Model
{
    /// <summary>
    /// TransferContractOwnershipRequest
    /// </summary>
    [DataContract]
    public partial class TransferContractOwnershipRequest :  IEquatable<TransferContractOwnershipRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferContractOwnershipRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TransferContractOwnershipRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TransferContractOwnershipRequest" /> class.
        /// </summary>
        /// <param name="ownerAddress">A wallet address to assign as the new owner and administrator of the target smart contract. (required).</param>
        public TransferContractOwnershipRequest(string ownerAddress = default(string))
        {
            // to ensure "ownerAddress" is required (not null)
            if (ownerAddress == null)
            {
                throw new InvalidDataException("ownerAddress is a required property for TransferContractOwnershipRequest and cannot be null");
            }
            else
            {
                this.OwnerAddress = ownerAddress;
            }

        }

        /// <summary>
        /// A wallet address to assign as the new owner and administrator of the target smart contract.
        /// </summary>
        /// <value>A wallet address to assign as the new owner and administrator of the target smart contract.</value>
        [DataMember(Name="ownerAddress", EmitDefaultValue=true)]
        public string OwnerAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TransferContractOwnershipRequest {\n");
            sb.Append("  OwnerAddress: ").Append(OwnerAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TransferContractOwnershipRequest);
        }

        /// <summary>
        /// Returns true if TransferContractOwnershipRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TransferContractOwnershipRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TransferContractOwnershipRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.OwnerAddress == input.OwnerAddress ||
                    (this.OwnerAddress != null &&
                    this.OwnerAddress.Equals(input.OwnerAddress))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OwnerAddress != null)
                    hashCode = hashCode * 59 + this.OwnerAddress.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
